export const QUERIES = {
  getHomePage: () => `*[_type == "home" && language == $language]{
    _id,
    bannerTitle,
    bannerSubTitle,
    "bannerImageUrl": bannerImage.asset->url,
    "bannerSlides": bannerSlides[]{
      title,
      subTitle,
      "imageUrl": image.asset->url,
    },
    liveYoutubeUrl,
    liveStartDateTime,
    themeTitle,
    themeMessage,
    themeVerse,
    "themeImageUrl": themeImage.asset->url,
    "themeLogoUrl": themeLogo.asset->url,
    whoWeAreTitle,
    whoWeAreMessage,
    "whoWeAreImageUrl": whoWeAreImage.asset->url,
    whoWeAreYoutubeUrl,
    language,
    "publishedDate": _updatedAt,
  }`,
  getLive: () => `*[_type == "live"]{
    youtubeId,
    startDateTime,
  }[0]`,
  getEvents: () => `*[_type == "event" && language == $language]{
    _id,
    title,
    slug,
    featured,
    startDateTime,
    venue,
    body,
    language,
    "imageUrl": mainImage.asset->url,
    recurring
  }`,
  getEventBySlug:
    () => `*[_type == "event" && language == $language && slug.current == $slug]{
    _id,
    title,
    slug,
    youtubeId,
    startDateTime,
    venue,
    body,
    language,
    "imageUrl": mainImage.asset->url,
  }`,
  getGalleryImages: () => `*[_type == "gallery"]{
    _id,
    title,
    "images": images[].asset->url
  }`,
  getPosts: () => `*[_type == "post" && language == $language]{
    _id,
    title,
    slug,
    body,
    language,
    "publishedDate": _updatedAt,
    "imageUrl": mainImage.asset->url,
  }`,
  getPostBySlug:
    () => `*[_type == "post" && language == $language && slug.current == $slug]{
    _id,
    title,
    slug,
    body,
    language,
    "publishedDate": _updatedAt,
    "imageUrl": mainImage.asset->url,
  }`,
  getTeam: () => `*[_type == "team" && language == $language]{
  _id,
  name,
  slug,
  position,
  biography,
  "publishedDate": _updatedAt,
  "imageUrl": image.asset->url,
  facebook,
  linkedin,
  language
}`,
  getTestimonials: () => `*[_type == "testimonials"]{
  _id,
  name,
  slug,
  message,
  "publishedDate": _updatedAt,
  "imageUrl": image.asset->url,
}`,
  getFooter: () => `*[_type == "footer" && language == $language]{
  _id,
  about,
  bankDetails,
  banker,
  language,
  "publishedDate": _updatedAt,
}`,
};
